### ISSUE TITLE
pdf-stats என்பதில் மாற்றம் தேவை

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/tools-for-wiki#1]
ஒரு கோப்புரையில் இருக்கும் மின்னூல் விவரங்களை நிரல் தருகிறது. ஒரு கோப்புரையில் பல உள்கோப்புரைகள்(subfoler) இருக்கிறது என்று வைத்துக் கொள்ளும். அதனுள்ளும் மின்னூல்கள் இருக்கின்றன. இச்சூழலில்,  pdf-stats நிரலை இயக்கினாலும், மின்னூல் விவரங்கள் வர, நிரல்மாற்றம் செய்யக் கோருகிறேன். இதுபோல, ஏறத்தாழ 100 கோப்புகளில், 4500 மின்னூல்கள் உள்ளன. ஒரு பயனர் தான் பதிவிறக்க விரும்பும், மின்னூலைப் பற்றி முழுமையாக தெரிந்து கொள்ள, இந்நிரலாக்கம் அளப்பரிய பணிசெய்கிறது. வாழ்த்துக்கள். வணக்கம்.

**Comment by tshrinivasan** [comment]
Fixed this.
