### ISSUE TITLE
Automate index creation

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/tools-for-wiki#12]
Once files are uploaded in Commons, automate index creation in Wikisource. 

Sample data for an index page - https://ta.wikisource.org/w/index.php?title=Index:%E0%AE%9A%E0%AE%BF%E0%AE%B2%E0%AE%AE%E0%AF%8D%E0%AE%AA%E0%AF%8A%E0%AE%B2%E0%AE%BF.pdf&action=edit

**Comment by tha-uzhavan** [comment]
Index making should be a stand alone tool because we going to run the tool for many times to maintain the Index.

**Comment by tshrinivasan** [comment]
Created index maker.

https://github.com/tshrinivasan/tools-for-wiki/tree/master/index-maker
