### ISSUE TITLE
pdf-upload-commons/ Is it  requires python 3.7 and above

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/tools-for-wiki#39]
பைத்தான்3 மாற்றியமைக்க உதவிய மோகனுக்கு நன்றி. $ DEV=1 ./bootstrap/bootstrap poetry shell என்ற கட்டளையை கொடுத்த போது, கீழ்கண்டவாறு முனையத்தில் (Terminal )வருகிறது. 

```
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
failed to install pip
```
பலர் லினக்சு மின்டு வழங்கல்களையே பயன்படுத்துகின்றனர். மேலும் பிற உபுண்டு வகைகளில் Python 3.6.9 பொதியே உள்ளது. எனவே, அதற்கொப்ப மாற்ற இயலுமா?  இயலாதெனின், பைத்தான் 3.7, பைத்தான் 3.8 க்கு மாற என்ன செய்ய வேண்டும்?

**Comment by tshrinivasan** [comment]
https://linuxhint.com/install-python-3-9-linux-mint/

check here
