### ISSUE TITLE
Book abstract service:  particular pdf page extraction need.

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/tools-for-wiki#5]
To do Book abstract service in ta.wiki like the following page
https://ta.wikipedia.org/s/3dxr. For that, first we have to separate cover pages(i.e. first page of 2500pdfs) from a pdf file. then we have to convert to png. For that i am  using  pdf-shuffler's export option. Then i am coverting the single page(book-cover) pdf file to png format by the following command "convert book-cover.pdf book-cover.png ". how to automate this process?

+ 5 minutes before, i found a pdftk command to get a page from a pdf-file.

" pdftk filename.pdf cat 1 output filecover.pdf" (filecoveri usally first page)

How can i automate, this command for a bunch of files in a folder.?

**Comment by tshrinivasan** [comment]
Check the folder 'get-cover-image-from-pdf'
and run the script in the folder with pdf files.

It will generate cover images for all the pdf files.
