### ISSUE TITLE
pdf-upload-commons

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/tools-for-wiki#7]
pyexiv - error.
How to install pyexiv2 in linuxmint17(ubuntu14)?
I solved the issue by https://apps.ubuntu.com/cat/applications/synaptic/
bye!

**Comment by tshrinivasan** [comment]
Edit the program and remove the line

import pyexiv2

Save the file and run the program.

Share the results.

**Comment by tha-uzhavan** [comment]
works well.

**Comment by tshrinivasan** [comment]
closing this.

**Comment by tshrinivasan** [comment]
closing this.
