### ISSUE TITLE
Remove underscore in Book Title

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/tools-for-wiki#8]
Check 

https://commons.wikimedia.org/wiki/File:%E0%AE%85%E0%AE%95%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AE%BF%E0%AE%A3%E0%AF%88%E0%AE%95%E0%AF%8D_%E0%AE%95%E0%AF%8A%E0%AE%B3%E0%AF%8D%E0%AE%95%E0%AF%88%E0%AE%95%E0%AE%B3%E0%AF%8D.pdf

In the Summary section, book title has a _ wherever a space should be there.

For example, it should be அகத்திணைக் கொள்கைகள் and not அகத்திணைக்_கொள்கைகள்

**Comment by tshrinivasan** [comment]
Now removed _ in the file name in summary section.

I checked the link. The original pdf file seems having _.

But still, removing it in summary section as you requested.

Are you adding the _ manually to filenames?

Check this.
https://github.com/tshrinivasan/OCR4wikisource/issues/35
